#!/bin/bash

# Update and install httpd
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd

# Create index.html file
cat << 'EOL' > /var/www/html/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Surf's Up!</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background-color: #e9f7f9;
        }
        header {
            background-color: #29b6f6;
            color: #ffffff;
            text-align: center;
            padding: 1em 0;
            font-size: 2em;
        }
        nav {
            display: flex;
            justify-content: space-around;
            background-color: #039be5;
        }
        nav a {
            color: white;
            text-decoration: none;
            padding: 1em;
        }
        nav a:hover {
            background-color: #0277bd;
        }
        .container {
            padding: 20px;
        }
        .section {
            background-color: white;
            margin: 10px;
            padding: 20px;
            border-radius: 8px;
        }
        h2, p {
            margin: 0 0 10px 0;
        }
        img {
            max-width: 100%; /* Ensures the image doesn't exceed its container's width */
        }
    </style>
</head>
<body>
    <header>
        Surf's Up!
    </header>
    <nav>
        <a href="#welcome">Home</a>
        <a href="#about">About Us</a>
        <a href="#contact">Contact</a>
    </nav>
    <div class="container">
        <div id="welcome" class="section">
            <h2>Welcome to Surf's Up!</h2>
            <p>Discover the finest surfboards and immerse yourself in the world of surfing.</p>
            <!-- Add your image from S3 here -->
            <img src="https://web-surf-s3.s3.amazonaws.com/rafael-leao-PzmmiWoJHA8-unsplash.jpg" alt="Surfboard" alt="Surfboard">
        </div>
        <div id="about" class="section">
            <h2>About Our Surfboards</h2>
            <p>Our surfboards are designed for surfers of all experience levels, offering the perfect balance between stability and maneuverability.</p>
        </div>
        <div id="contact" class="section">
            <h2>Contact Us</h2>
            <p>Email us at info@surfsup.com or call us at 123-456-7890 for any inquiries or support.</p>
        </div>
    </div>
</body>
</html>
EOL
